---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oadp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oadp-operator
  template:
    metadata:
      labels:
        name: oadp-operator
    spec:
      serviceAccountName: oadp-operator
      containers:
        - name: oadp-operator
          # Replace this with the built image name
          image: "quay.io/konveyor/oadp-operator:v0.2.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "oadp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: REGISTRY
              value: quay.io
            - name: PROJECT
              value: konveyor
            - name: VELERO_REPO
              value: velero
            - name: VELERO_OPENSHIFT_PLUGIN_REPO
              value: openshift-velero-plugin
            - name: VELERO_OPENSHIFT_PLUGIN_TAG
              value: release-1.4.0
            - name: VELERO_RESTIC_RESTORE_HELPER_REPO
              value: velero-restic-restore-helper
            - name: VELERO_AWS_PLUGIN_REPO
              value: velero-plugin-for-aws
            - name: VELERO_GCP_PLUGIN_REPO
              value: velero-plugin-for-gcp
            - name: VELERO_AZURE_PLUGIN_REPO
              value: velero-plugin-for-microsoft-azure
            - name: VELERO_CSI_PLUGIN_REPO
              value: velero-plugin-for-csi
            - name: VELERO_TAG
              value: konveyor-1.5.2
            - name: VELERO_RESTIC_RESTORE_HELPER_TAG
              value: latest
            - name: VELERO_AWS_PLUGIN_TAG
              value: konveyor-1.1.0
            - name: VELERO_GCP_PLUGIN_TAG
              value: konveyor-1.1.0
            - name: VELERO_AZURE_PLUGIN_TAG
              value: konveyor-1.1.0
            - name: VELERO_CSI_PLUGIN_TAG
              value: main
      volumes:
        - name: runner
          emptyDir: {}

