apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mssql-persistent
  namespace: openshift-adp
spec:
  includedNamespaces:
  - mssql-persistent
  storageLocation: velero-sample-1
  ttl: 720h0m0s
