language: bash
os: linux
services: docker
sudo: required
dist: bionic

env:
  global:
    IMAGE: quay.io/konveyor/oadp-operator
    DEFAULT_BRANCH: master
    DOCKERFILE: Dockerfile
jobs:
  include:
   - stage: build image
     arch: ppc64le
     script: ./.travis-build-image.sh
   - arch: amd64
     script: ./.travis-build-image.sh
   - arch: s390x
     script: ./.travis-build-image.sh
   - arch: arm64
     script: ./.travis-build-image.sh
   - stage: push manifest
     arch: x86_64
     script: ./.travis-push-manifest.sh
