## Append samples of your project ##
resources:
- oadp_v1alpha1_dataprotectionapplication.yaml
- backupstoragelocation.yaml
- deletebackuprequest.yaml
- downloadrequest.yaml
- podvolumebackup.yaml
- podvolumerestore.yaml
- resticrepository.yaml
- backup.yaml
- restore.yaml
- schedule.yaml
- serverstatusrequest.yaml
- volumesnapshotlocation.yaml
- oadp_v1alpha1_nonadminbackup.yaml
- oadp_v1alpha1_nonadminrestore.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
