apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: oadp-noobaa-obc
spec:
  bucketName: oadp-noobaa-bucket
  objectBucketName: oadp-noobaa-objectbucket
  storageClassName: openshift-storage.noobaa.io