---
backup_storage_locations: []
custom_velero_plugins: []
http_proxy: "{{ lookup( 'env', 'HTTP_PROXY') }}"
https_proxy: "{{ lookup( 'env', 'HTTPS_PROXY') }}"
no_proxy: "{{ lookup( 'env', 'NO_PROXY') }}"
image_pull_policy: Always
registry: "{{ lookup( 'env', 'REGISTRY') }}"
project: "{{ lookup( 'env', 'PROJECT') }}"
velero_namespace: "{{ lookup( 'env', 'WATCH_NAMESPACE') | default('oadp-operator') }}"
velero_state: "present"
velero_aws_bsl_configs: 0
velero_gcp_bsl_configs: 0
velero_azure_bsl_configs: 0
velero_aws_secret_name: cloud-credentials
velero_gcp_secret_name: gcp-cloud-credentials
velero_azure_secret_name: azure-cloud-credentials
velero_debug: false
velero_upstream_project: velero
velero_vsphere_upstream_project: vsphereveleroplugin
velero_upstream_tag: v1.5.2
velero_upstream_plugin_tag: main
velero_image: "{{ registry }}/{{ project }}/{{ velero_repo }}"
velero_repo: "{{ lookup( 'env', 'VELERO_REPO') }}"
velero_version: "{{ lookup( 'env', 'VELERO_TAG') }}"
velero_image_fqin: "{{ velero_image }}:{{ velero_version }}"
velero_openshift_plugin_image: "{{ registry }}/{{ project }}/{{ velero_openshift_plugin_repo }}"
velero_openshift_plugin_repo: "{{ lookup( 'env', 'VELERO_OPENSHIFT_PLUGIN_REPO') }}"
velero_openshift_plugin_version: "{{ lookup( 'env', 'VELERO_OPENSHIFT_PLUGIN_TAG') }}"
velero_csi_plugin_image: "{{ upstream_registry }}/{{ velero_upstream_project }}/{{ velero_csi_plugin_repo }}"
velero_csi_plugin_repo: "{{ lookup('env', 'VELERO_CSI_PLUGIN_REPO') }}"
velero_csi_plugin_version: "{{ lookup('env', 'VELERO_CSI_PLUGIN_TAG') }}"
velero_vsphere_plugin_image: "{{ upstream_registry }}/{{ velero_vsphere_upstream_project }}/{{ velero_vsphere_plugin_repo }}" # TODO: Remove this. Vsphere won't be supported
velero_vsphere_plugin_repo: "{{ lookup('env', 'VELERO_VSPHERE_PLUGIN_REPO') }}"
velero_vsphere_plugin_version: "{{ lookup('env', 'VELERO_VSPHERE_PLUGIN_TAG') }}"
velero_restic_restore_helper_image: "{{ registry }}/{{ project }}/{{ velero_restic_restore_helper_repo }}"
velero_restic_restore_helper_repo: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_REPO') }}"
velero_restic_restore_helper_version: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_TAG') }}"
velero_aws_plugin_image: "{{ registry }}/{{ project }}/{{ velero_aws_plugin_repo }}"
velero_aws_plugin_repo: "{{ lookup( 'env', 'VELERO_AWS_PLUGIN_REPO') }}"
velero_aws_plugin_version: "{{ lookup( 'env', 'VELERO_AWS_PLUGIN_TAG') }}"
velero_gcp_plugin_image: "{{ registry }}/{{ project }}/{{ velero_gcp_plugin_repo }}"
velero_gcp_plugin_repo: "{{ lookup( 'env', 'VELERO_GCP_PLUGIN_REPO') }}"
velero_gcp_plugin_version: "{{ lookup( 'env', 'VELERO_GCP_PLUGIN_TAG') }}"
velero_azure_plugin_image: "{{ registry }}/{{ project }}/{{ velero_azure_plugin_repo }}"
velero_azure_plugin_repo: "{{ lookup( 'env', 'VELERO_AZURE_PLUGIN_REPO') }}"
velero_azure_plugin_version: "{{ lookup( 'env', 'VELERO_AZURE_PLUGIN_TAG') }}"
velero_registry_tag: "{{ lookup( 'env', 'VELERO_REGISTRY_TAG') }}"
velero_registry_repo: "{{ lookup( 'env', 'VELERO_REGISTRY_REPO') }}"
velero_registry_image: "{{ registry }}/{{ project }}/{{ registry_image_repo }}"
restic_pv_host_path: /var/lib/kubelet/pods
restic_timeout: 1h
size: 1
volume_snapshot_locations: []
enable_restic: true
upstream_registry: docker.io
quay_registry: quay.io
konveyor_project: konveyor

# noobaa integration
noobaa: false
noobaa_crds_count: 0
noobaa_expected_crds:
  - noobaas.noobaa.io
  - bucketclasses.noobaa.io
  - backingstores.noobaa.io
noobaa_admin_secret: noobaa-admin
noobaa_system_namespace: openshift-storage
noobaa_system_pv_pool_bs_name: oadp-storage-pv-pool-backing-store
noobaa_system_pool_pv_quantity: 3
noobaa_system_pv_pool_pv_size: 30Gi
noobaa_system_pv_pool_pv_storageclass: gp2
noobaa_system_pv_pool_bc_name: oadp-storage-pv-pool-bucket-class
noobaa_system_pv_pool_bucket_name: oadp-storage-pv-pool-bucket-claim
noobaa_oadp_bucket_name: oadp-operator-pv-pool-bucket
noobaa_s3_endpoint_proto: https
noobaa_system_core_cpu: 100m
noobaa_system_core_mem: 400Mi
noobaa_system_db_cpu: 100m
noobaa_system_db_mem: 400Mi
noobaa_system_endpoints_cpu: 1
noobaa_system_endpoints_mem: 400Mi
noobaa_system_endpoints_pod_count: 1
