---
backup_storage_locations: []
custom_velero_plugins: []
http_proxy: "{{ lookup( 'env', 'HTTP_PROXY') }}"
https_proxy: "{{ lookup( 'env', 'HTTPS_PROXY') }}"
no_proxy: "{{ lookup( 'env', 'NO_PROXY') }}"
image_pull_policy: Always
registry: "{{ upstream_registry if use_upstream_images is defined and use_upstream_images|bool == true else lookup( 'env', 'REGISTRY') }}"
project: "{{ velero_upstream_project if use_upstream_images is defined and use_upstream_images|bool == true else lookup( 'env', 'PROJECT') }}"
velero_namespace: "{{ lookup( 'env', 'WATCH_NAMESPACE') | default('oadp-operator') }}"
velero_state: "present"
velero_aws_bsl_configs: 0
velero_gcp_bsl_configs: 0
velero_azure_bsl_configs: 0
velero_aws_secret_name: cloud-credentials
velero_gcp_secret_name: gcp-cloud-credentials
velero_azure_secret_name: azure-cloud-credentials
velero_debug: false
velero_upstream_project: velero
velero_upstream_tag: v1.4.0
velero_image: "{{ registry }}/{{ project }}/{{ velero_repo }}"
velero_repo: "{{ lookup( 'env', 'VELERO_REPO') }}"
velero_version: "{{ velero_upstream_tag if use_upstream_images is defined and use_upstream_images|bool == true else lookup( 'env', 'VELERO_TAG') }}"
velero_image_fqin: "{{ velero_image }}:{{ velero_version }}"
velero_openshift_plugin_image: "{{ quay_registry }}/{{ konveyor_project }}/{{ velero_openshift_plugin_repo }}"
velero_openshift_plugin_repo: "{{ lookup( 'env', 'VELERO_OPENSHIFT_PLUGIN_REPO') }}"
velero_openshift_plugin_version: "{{ lookup( 'env', 'VELERO_OPENSHIFT_PLUGIN_TAG') }}"
velero_csi_plugin_image: "{{ upstream_registry }}/{{ velero_upstream_project }}/{{ velero_csi_plugin_repo }}"
velero_csi_plugin_repo: "{{ lookup('env', 'VELERO_CSI_PLUGIN_REPO') }}"
velero_csi_plugin_version: "{{ lookup('env', 'VELERO_CSI_PLUGIN_TAG') }}"
velero_restic_restore_helper_image: "{{ registry }}/{{ project }}/{{ velero_restic_restore_helper_repo }}"
velero_restic_restore_helper_repo: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_REPO') }}"
velero_restic_restore_helper_version: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_TAG') }}"
velero_aws_plugin_image: "{{ registry }}/{{ project }}/{{ velero_aws_plugin_repo }}"
velero_aws_plugin_repo: "{{ lookup( 'env', 'VELERO_AWS_PLUGIN_REPO') }}"
velero_aws_plugin_version: "{{ lookup( 'env', 'VELERO_AWS_PLUGIN_TAG') }}"
velero_gcp_plugin_image: "{{ registry }}/{{ project }}/{{ velero_gcp_plugin_repo }}"
velero_gcp_plugin_repo: "{{ lookup( 'env', 'VELERO_GCP_PLUGIN_REPO') }}"
velero_gcp_plugin_version: "{{ lookup( 'env', 'VELERO_GCP_PLUGIN_TAG') }}"
velero_azure_plugin_image: "{{ registry }}/{{ project }}/{{ velero_azure_plugin_repo }}"
velero_azure_plugin_repo: "{{ lookup( 'env', 'VELERO_AZURE_PLUGIN_REPO') }}"
velero_azure_plugin_version: "{{ lookup( 'env', 'VELERO_AZURE_PLUGIN_TAG') }}"
restic_pv_host_path: /var/lib/kubelet/pods
restic_timeout: 1h
size: 1
volume_snapshot_locations: []
enable_restic: true
upstream_registry: docker.io
quay_registry: quay.io
konveyor_project: konveyor

# MCG integration
noobaa: false
noobaa_expected_crds:
  - noobaas.noobaa.io
  - bucketclasses.noobaa.io
  - backingstores.noobaa.io
noobaa_admin_secret: noobaa-admin
noobaa_system_namespace: "{{ velero_namespace }}"
noobaa_system_pv_pool_bs_name: mig-storage-pv-pool-backing-store
noobaa_system_pool_pv_quantity: 3
noobaa_system_pv_pool_pv_size: 50Gi
noobaa_system_pv_pool_pv_storageclass: gp2
noobaa_system_pv_pool_bc_name: mig-storage-pv-pool-backing-class
noobaa_system_pv_pool_bucket_name: mig-store-bucket
noobaa_mig_bucket_name: mig-storage
noobaa_s3_endpoint_proto: http
noobaa_system_core_cpu: 0.5
noobaa_system_core_mem: 500Mi
noobaa_system_db_cpu: 0.5
noobaa_system_db_mem: 1Gi
noobaa_system_endpoints_cpu: 1
noobaa_system_endpoints_mem: 500Mi
noobaa_system_endpoints_pod_count: 2
