# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/oadp.openshift.io_dataprotectionapplications.yaml
- bases/oadp.openshift.io_cloudstorages.yaml
- bases/velero.io_backuprepositories.yaml
- bases/velero.io_backups.yaml
- bases/velero.io_backupstoragelocations.yaml
- bases/velero.io_datadownloads.yaml
- bases/velero.io_datauploads.yaml
- bases/velero.io_deletebackuprequests.yaml
- bases/velero.io_downloadrequests.yaml
- bases/velero.io_podvolumebackups.yaml
- bases/velero.io_podvolumerestores.yaml
- bases/velero.io_restores.yaml
- bases/velero.io_schedules.yaml
- bases/velero.io_serverstatusrequests.yaml
- bases/velero.io_volumesnapshotlocations.yaml
- bases/oadp.openshift.io_nonadminbackups.yaml
- bases/oadp.openshift.io_nonadminrestores.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_dataprotectionapplications.yaml
#- path: patches/webhook_in_cloudstorages.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_dataprotectionapplications.yaml
#- path: patches/cainjection_in_cloudstorages.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
